name: tic-tac-toe

static_sites:
- name: client
  github:
    repo: MaxWaterfall/tic-tac-toe
    branch: main
    deploy_on_push: true
  source_dir: clients/svelte
  build_command: npm install && npm run build
  output_dir: public
  routes:
  - path: /

services:
  - name: server
    github:
      repo: MaxWaterfall/tic-tac-toe
      branch: main
      deploy_on_push: true
    source_dir: servers/kotlin-spring
    build_command: ./mvnw clean verify
    dockerfile_path: servers/kotlin-spring/Dockerfile