name: tic-tac-toe

static_sites:
- name: client
  github:
    repo: MaxWaterfall/tic-tac-toe
    branch: main
    deploy_on_push: false
  source_dir: clients/svelte
  build_command: npm install && npm run build
  output_dir: public
  routes:
  - path: /

services:
- name: server
  github:
    repo: MaxWaterfall/tic-tac-toe
    branch: main
    deploy_on_push: false
  source_dir: servers/kotlin-spring
  dockerfile_path: servers/kotlin-spring/Dockerfile
  routes:
  - path: /server